{% set version = "2.7.0" %}

package:
  name: tensorflow-split
  version: {{ version }}

source:
  - url: https://github.com/tensorflow/tensorflow/archive/refs/tags/v{{ version }}.tar.gz
    sha256: bb124905c7fdacd81e7c842b287c169bbf377d29c74c9dacc04f96c9793747bb
    patches:
      - patches/0001-relax-tolerence-in-special_math_test.patch
      - patches/0002-skip-read-only-debugger_cli_common-test.patch
      - patches/0003-relax-precision-in-matrix_log_op_test.patch
      # requires setting GRPCIO_VERSION in build script
      #- patches/0004-Fixup-requirements.patch
      - patches/0005-Replace-deprecated-absl-Status-error_message-call-wi.patch
  - url: https://github.com/tensorflow/estimator/archive/refs/tags/v{{ version }}.tar.gz
    sha256: e5164e802638d3cf110ecc17912be9d514a9d3354ec48e77200b9403dcc15965
    folder: tensorflow-estimator

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}                 # [cuda_compiler_version != "None"]
    - bazel
    - bazel >=4.2.1  # [osx and arm64]
    #- grpc-cpp
    - libprotobuf
    - nasm
    - sed
    - rsync  # [linux]
    # realpath is not available from the docker image for cuda <= 10.2
    # so we install coreutils here
    - coreutils  # [cuda_compiler_version != "None"]
  host:
    # GPU requirements for CUDA
    - cudnn      # [cuda_compiler_version != "None"]
    - nccl       # [cuda_compiler_version != "None"]
    # conda build requirements
    - python
    - pip
    - zlib
    - libpng
    - libcurl
    - curl         # [win]
    - unzip        # [not win]
    - zip          # [not win]
    - m2-unzip     # [win]
    - m2-zip       # [win]
    - openjdk >=8
    - nsync
    # TF_SYSTEM_LIBS
    - astor
    - cython
    - dill
    - giflib
    #- grpc-cpp
    - flatbuffers
    - icu
    - jpeg
    - jsoncpp
    - libpng
    - libprotobuf
    - openssl
    - pybind11
    - sqlite
    - snappy
    - zlib
    - abseil-cpp
    # requirements specified by the package itself, see
    # github.com/tensorflow/tensorflow/blob/v{{ version }}/tensorflow/tools/pip_package/setup.py
    - absl-py >=0.4.0
    - astunparse >=1.6.0
    - gast >=0.2.1,<0.5.0
    - google-pasta >=0.1.1
    - h5py >=2.9.0
    - keras-preprocessing >=1.1.1
    - numpy
    - opt_einsum >=2.3.2
    - protobuf >=3.9.2
    - python-flatbuffers >=1.12,<3
    - six >=1.12
    - tensorflow-io-gcs-filesystem >=0.21.0
    - termcolor >=1.1.0
    - typing_extensions >=3.6.6
    - wheel >=0.32,<1
    - wrapt >=1.11.0
    # TF-API needs to move in sync
    # XXX: actually, TF 2.7.0 still demands tb 2.6
    - tensorboard >=2.6,<2.7
    - keras >=2.7,<2.8

outputs:
  # as of tensorflow 2.7.0, we don't need tensorflow-base anymore;
  # we still build it as a compatibility output (see below), but the
  # main package is being built in the "tensorflow" output directly.
  - name: tensorflow
    script: build_pkg.sh  # [not win]
    script: build_pkg.bat  # [win]
    build:
      string: cuda{{ cuda_compiler_version | replace('.', '') }}py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version != "None"]
      string: cpu_py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version == "None"]
      # weigh down cpu implementation and give cuda preference
      track_features:
        - tensorflow-cpu          # [cuda_compiler_version == "None"]
      entry_points:
        - toco_from_protos = tensorflow.lite.toco.python.toco_from_protos:main
        - tflite_convert = tensorflow.lite.python.tflite_convert:main
        - toco = tensorflow.lite.python.tflite_convert:main
        - saved_model_cli = tensorflow.python.tools.saved_model_cli:main
        # The tensorboard package adds this entry point.
        # - tensorboard = tensorboard.main:run_main
        - tf_upgrade_v2 = tensorflow.tools.compatibility.tf_upgrade_v2_main:main
        - estimator_ckpt_converter = tensorflow_estimator.python.estimator.tools.checkpoint_converter:main
    requirements:
      # build requirements needs to pick up the compiler run_exports
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ compiler('cuda') }}  # [cuda_compiler_version != "None"]
      host:
        # GPU reuqirements
        - cudnn                   # [cuda_compiler_version != "None"]
        - nccl                    # [cuda_compiler_version != "None"]
        # conda build requirements
        - python
        - pip
        # TF_SYSTEM_LIBS
        - astor
        - cython
        - dill
        - giflib
        #- grpc-cpp
        - abseil-cpp
        - flatbuffers
        - icu
        - jpeg
        - jsoncpp
        - libcurl
        - libpng
        - libprotobuf
        - openssl
        - pybind11
        - snappy
        - sqlite
        - zlib
        # requirements specified by the package itself
        - absl-py >=0.4.0
        - astunparse >=1.6.0
        - gast >=0.2.1,<0.5.0
        - google-pasta >=0.1.1
        - h5py >=2.9.0
        - keras-preprocessing >=1.1.1
        - numpy
        - opt_einsum >=2.3.2
        - protobuf >=3.9.2
        - python-flatbuffers >=1.12,<3
        - six >=1.12
        - tensorflow-io-gcs-filesystem >=0.21.0
        - termcolor >=1.1.0
        - typing_extensions >=3.6.6
        - wheel >=0.32,<1
        - wrapt >=1.11.0
        # TF-API needs to move in sync
        # XXX: actually, TF 2.7.0 still demands tb 2.6
        - tensorboard >=2.6,<2.7
        - keras >=2.7,<2.8
      run:
        - python
        - absl-py >=0.4.0
        - astunparse >=1.6.0
        - gast >=0.2.1,<0.5.0
        - google-pasta >=0.1.1
        - grpcio >=1.24.3,<2.0 
        - h5py >=2.9.0
        - keras-preprocessing >=1.1.1
        - {{ pin_compatible('numpy') }}
        - opt_einsum >=2.3.2
        - protobuf >=3.9.2
        - python-flatbuffers >=1.12,<3
        - six >=1.12
        - tensorflow-io-gcs-filesystem >=0.21.0
        - termcolor >=1.1.0
        - typing_extensions >=3.6.6
        - wheel >=0.32,<1
        - wrapt >=1.11.0
        # TF-API needs to move in sync
        # XXX: actually, TF 2.7.0 still demands tb 2.6
        - tensorboard >=2.6,<2.7
        - keras >=2.7,<2.8
        # avoid that people without GPUs needlessly download ~0.5-1GB
        - __cuda  # [cuda_compiler_version != "None"]
    test:
      files:
        - test_tensorflow.py
      commands:
        - cat test_tensorflow.py    # [unix]
        - python test_tensorflow.py
        - tf_upgrade_v2 --help
        - saved_model_cli --help
        - tflite_convert --help     # [not win]
        - toco_from_protos --help   # [not win]
        - toco --help               # [not win]

  - name: tensorflow-estimator
    script: build_estimator.sh   # [not win]
    script: build_estimator.bat  # [win]
    build:
      string: cuda{{ cuda_compiler_version | replace('.', '') }}py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version != "None"]
      string: cpu_py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version == "None"]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        # Keep the cuda compiler here since it helps package solvers
        # decide on the cuda variant
        # https://github.com/conda-forge/tensorflow-feedstock/issues/162
        - {{ compiler('cuda') }}                 # [cuda_compiler_version != "None"]
        - bazel
        - bazel >=4.2.1  # [osx and arm64]
      host:
        - python
        - pip
        - setuptools
        - wheel
        # This ensures that a consistent version of openssl is chosen between
        # all packages.
        # https://github.com/conda-forge/conda-forge.github.io/issues/1528
        - openssl
        - {{ pin_subpackage('tensorflow', exact=True) }}
      run:
        - python
        - {{ pin_subpackage('tensorflow', exact=True) }}
    test:
      requires:
        - pip
      #commands:
        #- pip check

  - name: libtensorflow_cc
    script: cp_libtensorflow_cc.sh
    build:
      skip: true  # [not linux]
      string: cuda{{ cuda_compiler_version | replace('.', '') }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version != "None"]
      string: cpu_h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version == "None"]
      run_exports:
        # tensorflow makes no ABI guarantees, need to pin to what we built with
        - libtensorflow_cc {{ version }}
    requirements:
      # build requirements needs to pick up the compiler run_exports
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        # Keep the cuda compiler here since it helps package solvers
        # decide on the cuda variant
        # https://github.com/conda-forge/tensorflow-feedstock/issues/162
        - {{ compiler('cuda') }}  # [cuda_compiler_version != "None"]
      # host requirements to pick up run_exports
      host:
        - nccl                    # [cuda_compiler_version != "None"]
        - giflib
        #- grpc-cpp
        - abseil-cpp
        - icu
        - jpeg
        - jsoncpp
        - libcurl
        - libpng
        - libprotobuf
        - openssl
        - snappy
        - sqlite
        - zlib
      run:
        # avoid that people without GPUs needlessly download ~200-300MB
        - intel-openmp
        - __cuda  # [cuda_compiler_version != "None"]
    test:
      files:
        - test_libtensorflow_cc.sh
        - test_cc.cc
      requires:
        - {{ compiler('cxx') }}
      commands:
        - test -f $PREFIX/lib/libtensorflow_cc.so  # [not win and cuda_compiler_version == "None"]
        #- ./test_libtensorflow_cc.sh               # [not win and cuda_compiler_version == "None"]

about:
  home: http://tensorflow.org/
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  summary: An Open Source Machine Learning Framework for Everyone.
  description: |
    TensorFlow provides multiple APIs. The lowest level API, TensorFlow Core
    provides you with complete programming control.
  dev_url: https://github.com/tensorflow/tensorflow
  doc_url: https://www.tensorflow.org/get_started/get_started
  doc_source_url: https://github.com/tensorflow/tensorflow/tree/master/tensorflow/docs_src

extra:
  feedstock-name: tensorflow
  recipe-maintainers:
    - farhantejani
    - ghego
    - h-vetinari
    - hajapy
    - jschueller
    - njzjz
    - waitingkuo
    - xhochy
    - hmaarrfk
    - wolfv
